# Generated by Django 3.2.10 on 2022-01-28 09:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=tinymce.models.HTMLField(default='a'),
            preserve_default=False,
        ),
    ]
