# Generated by Django 3.2.11 on 2022-01-29 09:40

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=django_quill.fields.QuillField(default='content'),
            preserve_default=False,
        ),
    ]
