# Generated by Django 3.2.11 on 2022-01-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_project_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
    ]
