# Generated by Django 3.2.11 on 2022-01-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
