# Generated by Django 3.2.10 on 2022-01-28 17:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor.fields.RichTextField(default='content'),
            preserve_default=False,
        ),
    ]
