# Generated by Django 3.2.11 on 2022-01-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_contactme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resume_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='resume_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
