# Generated by Django 3.2.11 on 2022-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='ici'),
        ),
    ]
